//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 08:56:33 AM CDT 
//


package com.ups.xolt.codesamples.request.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemizedBillThirdPartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemizedBillThirdPartyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="BillThirdPartyShipper" type="{}BillThirdPartyShipperType" minOccurs="0"/&gt;
 *         &lt;element name="BillThirdPartyConsignee" type="{}BillThirdPartyConsigneeType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemizedBillThirdPartyType", propOrder = {
    "billThirdPartyShipper",
    "billThirdPartyConsignee"
})
public class ItemizedBillThirdPartyType {

    @XmlElement(name = "BillThirdPartyShipper")
    protected BillThirdPartyShipperType billThirdPartyShipper;
    @XmlElement(name = "BillThirdPartyConsignee")
    protected BillThirdPartyConsigneeType billThirdPartyConsignee;

    /**
     * Gets the value of the billThirdPartyShipper property.
     * 
     * @return
     *     possible object is
     *     {@link BillThirdPartyShipperType }
     *     
     */
    public BillThirdPartyShipperType getBillThirdPartyShipper() {
        return billThirdPartyShipper;
    }

    /**
     * Sets the value of the billThirdPartyShipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillThirdPartyShipperType }
     *     
     */
    public void setBillThirdPartyShipper(BillThirdPartyShipperType value) {
        this.billThirdPartyShipper = value;
    }

    /**
     * Gets the value of the billThirdPartyConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link BillThirdPartyConsigneeType }
     *     
     */
    public BillThirdPartyConsigneeType getBillThirdPartyConsignee() {
        return billThirdPartyConsignee;
    }

    /**
     * Sets the value of the billThirdPartyConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillThirdPartyConsigneeType }
     *     
     */
    public void setBillThirdPartyConsignee(BillThirdPartyConsigneeType value) {
        this.billThirdPartyConsignee = value;
    }

}
